A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('product.urls', namespace='product')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

dashboard/urls.py
from django.urls import path

from .views import (home,
                    add_product,
                    product_list,
                    product_edit,
                    one_brand_cat_choose,
                    two_product,
                    add_brand,
                    three_attribute,
                    four_images,
                    test,
                    )



app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home'),
    path('add_product/', add_product, name='add-product'),
    path('product_list/', product_list, name='product-list'),
    path('product_edit/<int:id>', product_edit, name='product-edit'),
    path('add_brand/', add_brand, name='add-brand'),
    path('test/', test, name='test'),

    # 4 Steps:
    path('one_brand_cat_choose/', one_brand_cat_choose, name='one-brand-cat-choose'),
    path('two_product/<str:category>/<str:brand>/', two_product, name='two-product'),
    path('three_attribute/<str:product>/', three_attribute, name='three-attribute'),
    path('four_images/<str:product>/', four_images, name='four-images'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django.forms import ModelForm, Textarea, widgets, FileField
from product.models import Brand, Product, Category, ProductAttribute, Images
from django import forms




class ProductForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.category = kwargs.pop('category', None)
        self.brand = kwargs.pop('brand', None)
        super().__init__(*args, **kwargs)
        category_obj = Category.objects.filter(title=self.category).first()
        self.fields['category'].initial = category_obj
        brand_obj = Brand.objects.filter(title=self.brand).first()
        self.fields['brand'].initial = brand_obj        

    class Meta:
        model = Product
        exclude = ['slug', 'date', ]
        widgets = {
            'detail': Textarea(attrs={'cols': 1, 'rows': 1}),
            'specs': Textarea(attrs={'cols': 1, 'rows': 1}),
        }



class BrandForm(ModelForm):
    class Meta:
        model = Brand
        exclude = ['detail', ]


class ProductAttributeForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.product = kwargs.pop('product', None)
        super().__init__(*args, **kwargs)
        product_obj = Product.objects.filter(title=self.product).first()
        self.fields['product'].initial = product_obj


    class Meta:
        model = ProductAttribute
        exclude = ['price', ]


class FileFieldForm(forms.Form):
    main_image = forms.ImageField()
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


class ImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['image', 'product']
        # widgets = {
        #     'image': forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True})),
        # }
        field_classes = {'image': forms.FileField}
        widgets = {'image': forms.ClearableFileInput(attrs={'multiple': True})}

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect

from product.models import Category, Product, Brand, Images
from .forms import ProductForm, BrandForm, ProductAttributeForm, ImageForm, FileFieldForm


def home(request):
    context = {}
    return render(request, 'dashboard/home.html', context)


def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST) 
        form.save()   
    else:
        form = ProductForm()
    context = {
        'form': form,
    }
    return render(request, 'dashboard/add_product.html', context)


def product_list(request):
    qs = Product.objects.all()
    context = {
        'products': qs,
    }
    return render(request, 'dashboard/product_list.html',context)


def product_edit(request, id):
    instance = get_object_or_404(Product, id=id)
    form = ProductForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('dashboard:product-list')
    context = {
        'form': form,
    }
    return render(request, 'dashboard/product_edit.html', context)


def one_brand_cat_choose(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()
    if request.method == 'POST':
        category = request.POST['select_categories']
        brand = request.POST['select_brand']
        return redirect('dashboard:two-product', category, brand)
    else:
        brand_form = BrandForm()
    context = {
        'categories': categories,
        'brands': brands,
        'brand_form': brand_form,
    }
    return render(request, 'dashboard/one_brand_cat_choose.html', context)


def two_product(request, category, brand):
    if request.method == 'POST':
        form = ProductForm(request.POST, category=category, brand=brand)  
        if form.is_valid():  
            product = form.save()
            return redirect('dashboard:three-attribute', product)
    else:
        form = ProductForm(category=category, brand=brand)  
    context = {
        'form': form,
    }
    return render(request, 'dashboard/two_product.html', context)


def three_attribute(request, product):
    if request.method == 'POST':
        form = ProductAttributeForm(request.POST, product=product)  
        if form.is_valid():  
            product = form.save()
            return redirect('dashboard:four-images', product)
    else:
        form = ProductAttributeForm(product=product)  
    context = {
        'form': form,
    }
    return render(request, 'dashboard/three_attribute.html', context)


def four_images(request, product):
    product = Product.objects.filter(title=product).first()
    if request.method == 'POST':
        form = FileFieldForm(request.POST)
        files = request.FILES.getlist('file_field')
        main_image = request.FILES.get('main_image')
        i = Images(image=main_image, product=product, is_main=True)
        i.save()
        for f in files:
            i = Images(image=f, product=product)
            i.save()
        return redirect('dashboard:home')
    else:
        form = FileFieldForm()
    context = {
        'form': form,
    }
    return render(request, 'dashboard/four_images.html', context)



def add_brand(request):
    if request.method == 'POST':
        form = BrandForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('dashboard:one-brand-cat-choose')
    else:
        return render(request, 'dashboard/one_brand_cat_choose.html')


def test(request):
    context = {}
    return render(request, 'dashboard/test.html', context)

dashboard/templates/dashboard/add_product.html
{% extends 'base.html' %}

{% block content %}
<h1>DASHBOARD - ADD product</h1>
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit">submit</button>
    
</form>
{% endblock %}

dashboard/templates/dashboard/four_images.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>DASHBOARD - Add Images</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>



{% endblock %}

dashboard/templates/dashboard/home.html
{% extends 'base.html' %}

{% block content %}
<h1>DASHBOARD - HOME</h1>
    <a href="{% url 'dashboard:add-product' %}">Add Product</a>
    <br/>
    <a href="{% url 'dashboard:product-list' %}">Product List</a>
    <br/>
    <a href="{% url 'dashboard:one-brand-cat-choose' %}">4 Step pro add</a>

</form>
{% endblock %}

dashboard/templates/dashboard/one_brand_cat_choose.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>DASHBOARD - Brand & Category Choose</h1>
<br/>
<div class="container">
    <div class="row">
      <div class="col-sm">
        <form method="POST">
            {% csrf_token %}
            <select id="select_categories" name="select_categories" class="form-control">
                <option>Choose Category</option>
                {% for category in categories %}
                    <option value="{{ category.title }}" id="{{ category.title }}" name="{{ brand.title }}">{{ forloop.counter }}. {{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-sm">
            <select id="select_brand" name="select_brand" class="form-control">
                <option>Choose Brand</option>
                {% for brand in brands %}
                    <option value="{{ brand.title }}" id="{{ brand.title }}" name="{{ brand.title }}" >{{ forloop.counter }}. {{ brand }}</option>
                {% endfor %}
            </select>
            <button type="submit" name="proceed" value="proceed">Proceed</button>
          </form>
      </div>
      <div class="col-sm">
        Add a New Brand
        <br/>
        <form action="{% url 'dashboard:add-brand' %}" method="POST">
          {% csrf_token %}
          {{ brand_form }}
          <button type="submit" name="add_brand" value="add_brand">Add Brand</button>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

dashboard/templates/dashboard/product_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>DASHBOARD - Product Edit</h1>
<br/>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <button type="submit">Submit</button>
</form>
{% endblock %}

dashboard/templates/dashboard/product_list.html
{% extends 'base.html' %}

{% block content %}
<h1>DASHBOARD - Product List</h1>
<br/>
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th scope="col">Brand</th>
        <th scope="col">Status</th>
        <th scope="col">Date</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
        {% for product in products %}
            <tr>
                <th scope="row">1</th>
                <td>{{ product.title }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.brand }}</td>
                <td>{{ product.status }}</td>
                <td>{{ product.date }}</td>
                <td><a href="{% url 'dashboard:product-edit' product.id %}">Edit</a> / <a href="">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>


{% endblock %}

dashboard/templates/dashboard/test.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'dashboard/snippets/steps.html' %}

{% endblock %}

dashboard/templates/dashboard/three_attribute.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>DASHBOARD - Add Attribute</h1>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
</form>



{% endblock %}

dashboard/templates/dashboard/two_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>DASHBOARD - Add Product</h1>
<br/>
<form method='POST'>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Add Product</button>
</form>


{% endblock %}