A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('product.urls', namespace='product')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

main/urls.py
from django.urls import path

from .views import home

app_name = 'main'

urlpatterns = [
    path('', home, name="home"),
]

product/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import list_view, product_catalog, cat_filter

app_name = 'product'

urlpatterns = [
    path('list-view/', list_view, name="list-view"),
    path('product-catalog/', product_catalog, name="product-catalog"),
    path('cat-filter/<slug:slug>/', cat_filter, name='category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'website/css/main.css' %}">

    
    <script type="text/javascript">
      var user = '{{request.user}}'
    </script>

    <title>MINI ECOM</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'main:home' %}">Ecom</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Store <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'product:list-view' %}">List View </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'product:product-catalog' %}">Product Catalog</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard:home' %}">Dashboard</a>
          </li>
        
        </ul>
        <div class="form-inline my-2 my-lg-0">
          <a href="#"class="btn btn-warning">Login</a>
          
          <a href="#">
             <img  id="cart-icon" src="{% static 'website/images/cart.png' %}">
         </a>
         <p id="cart-total">{{ order.get_cart_items }}</p>

          </div>
      </div>
    </nav>




    
    
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
    <script src="{% static 'website/js/csrf.ajax.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>